// src/redux/actionTypes.js
export const SET_FORM_DATA = "SET_FORM_DATA";
export const RESET_FORM = "RESET_FORM";

// src/redux/Booking/actionTypes.js
export const FETCH_TICKET_REQUEST = "FETCH_TICKET_REQUEST";
export const FETCH_TICKET_SUCCESS = "FETCH_TICKET_SUCCESS";
export const FETCH_TICKET_FAILURE = "FETCH_TICKET_FAILURE";

export const CANCEL_TICKET_REQUEST = "CANCEL_TICKET_REQUEST";
export const CANCEL_TICKET_SUCCESS = "CANCEL_TICKET_SUCCESS";
export const CANCEL_TICKET_FAILURE = "CANCEL_TICKET_FAILURE";