// src/redux/actionTypes.js
export const SET_FORM_DATA = "SET_FORM_DATA";
export const RESET_FORM = "RESET_FORM";

// src/redux/Booking/actionTypes.js
export const FETCH_AVAILABLESEATS_REQUEST = "FETCH_AVAILABLESEATS_REQUEST";
export const FETCH_AVAILABLESEATS_SUCCESS = "FETCH_AVAILABLESEATS_SUCCESS";
export const FETCH_AVAILABLESEATS_FAILURE = "FETCH_AVAILABLESEATS_FAILURE";

